/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
/**
 *
 * @author xp
 */
public class VentanaAhorcado extends javax.swing.JFrame {

  String palabraOculta = "CETYS"; 
  int numeroDeFallos = 0; 
  
  
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        dibujaImagen(0);
    } 
     private void chequeaLetra (String letra){ 
         letra = letra.toUpperCase();
         String palabraConGuiones = pantalla.getText();
         boolean acierto = false; 
         for (int i=0; i<palabraOculta.length(); i++){ 
             if(palabraOculta.charAt(i) == letra.charAt(0)){ 
                 //quita los guion bajo de la letra correspondiente 
                 palabraConGuiones = palabraConGuiones.substring(0, 2*i)
                 + letra 
                 + palabraConGuiones.substring(2*1 +1);
                 acierto = true;
         }
     } 
              pantalla.setText(palabraConGuiones);
         
         
      if(!acierto){ 
          numeroDeFallos++; 
          dibujaImagen(numeroDeFallos); 
          
      }
      }   

             
             
    private void chequeaBoton(JButton _boton){  
    _boton.setEnabled(false); 
    chequeaLetra(_boton.getText());
    
} 
private void dibujaImagen (int numeroImagen){ 
    URL nombreImagen; 
    String nombre = "";
    switch (numeroImagen){ 
        case 0 : nombre = "/imagenes/ahorcado_0.png"; break;
        case 1 : nombre = "/imagenes/ahorcado_1.png"; break;
        case 2 : nombre = "/imagenes/ahorcado_2.png"; break;
        case 3 : nombre = "/imagenes/ahorcado_3.png"; break;
        case 4 : nombre = "/imagenes/ahorcado_4.png"; break;
        case 5 : nombre = "/imagenes/ahorcado_5.png"; break;
       default : nombre = "/imagenes/ahorcado_fin.png"; break;
           
         
    }    
    nombreImagen = getClass().getResource(nombre);
            
            
            int ancho = panelAhorcado.getWidth(); 
            int alto = panelAhorcado.getHeight(); 
            ImageIcon miImagen = new ImageIcon( new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
            panelAhorcado.setIcon(miImagen);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letra25 = new javax.swing.JButton();
        letra27 = new javax.swing.JButton();
        letra22 = new javax.swing.JButton();
        letra28 = new javax.swing.JButton();
        letra23 = new javax.swing.JButton();
        letra26 = new javax.swing.JButton();
        letra24 = new javax.swing.JButton();
        pantalla = new javax.swing.JLabel();
        panelAhorcado = new javax.swing.JLabel();
        letra1 = new javax.swing.JButton();
        letra2 = new javax.swing.JButton();
        letra3 = new javax.swing.JButton();
        letra4 = new javax.swing.JButton();
        letra5 = new javax.swing.JButton();
        letra6 = new javax.swing.JButton();
        letra7 = new javax.swing.JButton();
        letra8 = new javax.swing.JButton();
        letra9 = new javax.swing.JButton();
        letra10 = new javax.swing.JButton();
        letra11 = new javax.swing.JButton();
        letra12 = new javax.swing.JButton();
        letra13 = new javax.swing.JButton();
        letra14 = new javax.swing.JButton();
        letra15 = new javax.swing.JButton();
        letra16 = new javax.swing.JButton();
        letra17 = new javax.swing.JButton();
        letra18 = new javax.swing.JButton();
        letra19 = new javax.swing.JButton();
        letra20 = new javax.swing.JButton();
        letra21 = new javax.swing.JButton();
        letra29 = new javax.swing.JButton();
        letra30 = new javax.swing.JButton();
        letra31 = new javax.swing.JButton();
        letra32 = new javax.swing.JButton();
        letra33 = new javax.swing.JButton();
        letra34 = new javax.swing.JButton();
        letra35 = new javax.swing.JButton();

        letra25.setText("D");
        letra25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra25MousePressed(evt);
            }
        });

        letra27.setText("F");
        letra27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra27MousePressed(evt);
            }
        });

        letra22.setText("A");
        letra22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra22MousePressed(evt);
            }
        });

        letra28.setText("G");
        letra28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra28MousePressed(evt);
            }
        });

        letra23.setText("B");
        letra23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra23MousePressed(evt);
            }
        });

        letra26.setText("E");
        letra26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra26MousePressed(evt);
            }
        });

        letra24.setText("C");
        letra24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra24MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 48)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pantalla.setText("_ _ _ _ _ _ _");

        panelAhorcado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        letra1.setText("A");
        letra1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra1MousePressed(evt);
            }
        });

        letra2.setText("B");
        letra2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra2MousePressed(evt);
            }
        });

        letra3.setText("C");
        letra3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra3MousePressed(evt);
            }
        });

        letra4.setText("D");
        letra4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra4MousePressed(evt);
            }
        });

        letra5.setText("E");
        letra5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra5MousePressed(evt);
            }
        });

        letra6.setText("F");
        letra6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra6MousePressed(evt);
            }
        });

        letra7.setText("G");
        letra7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra7MousePressed(evt);
            }
        });

        letra8.setText("H");
        letra8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra8MousePressed(evt);
            }
        });

        letra9.setText("I");
        letra9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra9MousePressed(evt);
            }
        });

        letra10.setText("J");
        letra10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra10MousePressed(evt);
            }
        });

        letra11.setText("K");
        letra11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra11MousePressed(evt);
            }
        });

        letra12.setText("L");
        letra12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra12MousePressed(evt);
            }
        });

        letra13.setText("M");
        letra13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra13MousePressed(evt);
            }
        });

        letra14.setText("N");
        letra14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra14MousePressed(evt);
            }
        });

        letra15.setText("Ñ");
        letra15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra15MousePressed(evt);
            }
        });
        letra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra15ActionPerformed(evt);
            }
        });

        letra16.setText("O");
        letra16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra16MousePressed(evt);
            }
        });

        letra17.setText("P");
        letra17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra17MousePressed(evt);
            }
        });

        letra18.setText("Q");
        letra18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra18MousePressed(evt);
            }
        });

        letra19.setText("R");
        letra19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra19MousePressed(evt);
            }
        });
        letra19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra19ActionPerformed(evt);
            }
        });

        letra20.setText("S");
        letra20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra20MousePressed(evt);
            }
        });

        letra21.setText("T");
        letra21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra21MousePressed(evt);
            }
        });
        letra21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra21ActionPerformed(evt);
            }
        });

        letra29.setText("U");
        letra29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra29MousePressed(evt);
            }
        });
        letra29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra29ActionPerformed(evt);
            }
        });

        letra30.setText("V");
        letra30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra30MousePressed(evt);
            }
        });
        letra30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra30ActionPerformed(evt);
            }
        });

        letra31.setText("W");
        letra31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra31MousePressed(evt);
            }
        });

        letra32.setText("X");
        letra32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra32MousePressed(evt);
            }
        });

        letra33.setText("Y");
        letra33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra33MousePressed(evt);
            }
        });

        letra34.setText("F");
        letra34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra34MousePressed(evt);
            }
        });

        letra35.setText("G");
        letra35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letra35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra35MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letra29, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letra30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letra31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letra32, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letra33, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letra34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letra35, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra29, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra32, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra33, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra35, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MousePressed
        chequeaBoton((JButton) evt.getSource()); 
    }//GEN-LAST:event_letra1MousePressed

    private void letra2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MousePressed
     chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra2MousePressed

    private void letra3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra3MousePressed

    private void letra4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra4MousePressed

    private void letra5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra5MousePressed

    private void letra6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra6MousePressed

    private void letra7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra7MousePressed

    private void letra8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra8MousePressed

    private void letra9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra9MousePressed

    private void letra10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra10MousePressed

    private void letra11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra11MousePressed

    private void letra12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra12MousePressed

    private void letra13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra13MousePressed

    private void letra14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra14MousePressed

    private void letra15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra15MousePressed

    private void letra16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra16MousePressed

    private void letra17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra17MousePressed

    private void letra18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra18MousePressed

    private void letra19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra19MousePressed

    private void letra20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra20MousePressed

    private void letra21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra21MousePressed

    private void letra22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra22MousePressed

    private void letra23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra23MousePressed

    private void letra24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra24MousePressed

    private void letra25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra25MousePressed

    private void letra26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra26MousePressed

    private void letra27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra27MousePressed

    private void letra28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra28MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra28MousePressed

    private void letra29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra29MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra29MousePressed

    private void letra30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra30MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra30MousePressed

    private void letra31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra31MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra31MousePressed

    private void letra32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra32MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra32MousePressed

    private void letra33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra33MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra33MousePressed

    private void letra34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra34MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra34MousePressed

    private void letra35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra35MousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_letra35MousePressed

    private void letra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra15ActionPerformed

    private void letra19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra19ActionPerformed

    private void letra29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra29ActionPerformed

    private void letra30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra30ActionPerformed

    private void letra21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton letra1;
    private javax.swing.JButton letra10;
    private javax.swing.JButton letra11;
    private javax.swing.JButton letra12;
    private javax.swing.JButton letra13;
    private javax.swing.JButton letra14;
    private javax.swing.JButton letra15;
    private javax.swing.JButton letra16;
    private javax.swing.JButton letra17;
    private javax.swing.JButton letra18;
    private javax.swing.JButton letra19;
    private javax.swing.JButton letra2;
    private javax.swing.JButton letra20;
    private javax.swing.JButton letra21;
    private javax.swing.JButton letra22;
    private javax.swing.JButton letra23;
    private javax.swing.JButton letra24;
    private javax.swing.JButton letra25;
    private javax.swing.JButton letra26;
    private javax.swing.JButton letra27;
    private javax.swing.JButton letra28;
    private javax.swing.JButton letra29;
    private javax.swing.JButton letra3;
    private javax.swing.JButton letra30;
    private javax.swing.JButton letra31;
    private javax.swing.JButton letra32;
    private javax.swing.JButton letra33;
    private javax.swing.JButton letra34;
    private javax.swing.JButton letra35;
    private javax.swing.JButton letra4;
    private javax.swing.JButton letra5;
    private javax.swing.JButton letra6;
    private javax.swing.JButton letra7;
    private javax.swing.JButton letra8;
    private javax.swing.JButton letra9;
    private javax.swing.JLabel panelAhorcado;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
